# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/jangbagooni_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jangbagooni_Form(object):
    def setupUi(self, jangbagooni_Form):
        jangbagooni_Form.setObjectName("jangbagooni_Form")
        jangbagooni_Form.resize(400, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(jangbagooni_Form.sizePolicy().hasHeightForWidth())
        jangbagooni_Form.setSizePolicy(sizePolicy)
        jangbagooni_Form.setMinimumSize(QtCore.QSize(400, 500))
        jangbagooni_Form.setMaximumSize(QtCore.QSize(400, 500))
        jangbagooni_Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(jangbagooni_Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(jangbagooni_Form)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_back = QtWidgets.QPushButton(self.widget)
        self.btn_back.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_back.setMaximumSize(QtCore.QSize(24, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_back.setFont(font)
        self.btn_back.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_back.setFlat(True)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(jangbagooni_Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(162, 162, 162);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_2)
        self.scrollArea = QtWidgets.QScrollArea(jangbagooni_Form)
        self.scrollArea.setStyleSheet("    QScrollArea {\n"
"        border: none;\n"
"    }\n"
"\n"
"    QScrollBar {\n"
"        background: white;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"\n"
"    QScrollBar:vertical {\n"
"        width: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::handle {\n"
"        background: gray;\n"
"        border-radius: 5px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:horizontal {\n"
"        height: 25px;\n"
"        min-width: 10px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        width: 25px;\n"
"        min-height: 10px;\n"
"    }\n"
"\n"
"    QScrollBar::add-line {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"\n"
"    QScrollBar::sub-line {\n"
"        border: none;\n"
"        background: none;\n"
"    }\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 388, 407))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout_5.addWidget(self.widget_3)
        self.widget_cart = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_cart.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_cart.setObjectName("widget_cart")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_cart)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.widget_cart)
        self.btn_more = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btn_more.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_more.setAutoFillBackground(False)
        self.btn_more.setStyleSheet("")
        self.btn_more.setDefault(False)
        self.btn_more.setFlat(True)
        self.btn_more.setObjectName("btn_more")
        self.verticalLayout_5.addWidget(self.btn_more)
        self.widget_23 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_23.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_23.setObjectName("widget_23")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_23)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_order = QtWidgets.QLabel(self.widget_23)
        self.label_order.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_order.setObjectName("label_order")
        self.gridLayout_2.addWidget(self.label_order, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_23)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 0, 1, 1)
        self.label_order2 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_order2.setFont(font)
        self.label_order2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_order2.setObjectName("label_order2")
        self.gridLayout_2.addWidget(self.label_order2, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget_23)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.widget_23)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn = QtWidgets.QPushButton(jangbagooni_Form)
        self.btn.setMinimumSize(QtCore.QSize(30, 0))
        self.btn.setStyleSheet("background-color: rgb(28, 251, 255);")
        self.btn.setObjectName("btn")
        self.verticalLayout.addWidget(self.btn)

        self.retranslateUi(jangbagooni_Form)
        QtCore.QMetaObject.connectSlotsByName(jangbagooni_Form)

    def retranslateUi(self, jangbagooni_Form):
        _translate = QtCore.QCoreApplication.translate
        jangbagooni_Form.setWindowTitle(_translate("jangbagooni_Form", "Form"))
        self.btn_back.setText(_translate("jangbagooni_Form", "←"))
        self.label.setText(_translate("jangbagooni_Form", "                            장바구니"))
        self.label_7.setText(_translate("jangbagooni_Form", "배민스토어"))
        self.label_3.setText(_translate("jangbagooni_Form", "대용량특가"))
        self.label_4.setText(_translate("jangbagooni_Form", "전국별미"))
        self.label_2.setText(_translate("jangbagooni_Form", "배달/포장"))
        self.label_5.setText(_translate("jangbagooni_Form", "피자쿠치나 광주소촌우산점"))
        self.label_6.setText(_translate("jangbagooni_Form", "45~60분후 도착"))
        self.btn_more.setText(_translate("jangbagooni_Form", "🞤 더 담으러 가기"))
        self.label_order.setText(_translate("jangbagooni_Form", "TextLabel"))
        self.label_28.setText(_translate("jangbagooni_Form", "총 주문금액 "))
        self.label_order2.setText(_translate("jangbagooni_Form", "TextLabel"))
        self.label_29.setText(_translate("jangbagooni_Form", "결제예정금액"))
        self.btn.setText(_translate("jangbagooni_Form", "주문하기"))
